export const Constants = {
    QUEUE_CRIAR_TRANSACOES: 'QUEUE_CRIAR_TRANSACOES',
    QUEUE_TRANSACOES_CRIADAS: 'QUEUE_TRANSACOES_CRIADAS',
    QUEUE_ALTERAR_TRANSACOES: 'QUEUE_ALTERAR_TRANSACOES',
    QUEUE_TRANSACOES_ALTERADAS: 'QUEUE_TRANSACOES_ALTERADAS',
    QUEUE_EXCLUIR_TRANSACOES: 'QUEUE_EXCLUIR_TRANSACOES',
    QUEUE_TRANSACOES_EXCLUIDAS: 'QUEUE_TRANSACOES_EXCLUIDAS',
}