DROP DATABASE FINANCEIRO;
CREATE DATABASE FINANCEIRO;

USE FINANCEIRO;

-- TABELAS DA APLICACAO
CREATE TABLE APP_CONTA (
    ID CHAR(36) PRIMARY KEY,
    NOME VARCHAR(144) NOT NULL,
    RAZAO_SOCIAL VARCHAR(144) NOT NULL,
    IDENTIFICADOR_FISCAL VARCHAR(14) NOT NULL UNIQUE -- CPF: 11, CNPJ: 14
);

CREATE TABLE APP_UNIDADEORGANIZACIONAL (
    ID CHAR(36) PRIMARY KEY,
    CODIGO VARCHAR(6) NOT NULL,
    NOME VARCHAR(255) NOT NULL,

    ID_CONTA CHAR(36) NOT NULL,
    ID_PAI CHAR(36) NULL,

    FOREIGN KEY (ID_CONTA) REFERENCES APP_CONTA(ID),
    FOREIGN KEY (ID_PAI) REFERENCES APP_UNIDADEORGANIZACIONAL(ID)
);

CREATE TABLE APP_USUARIO (
    ID CHAR(36) PRIMARY KEY,
    LOGIN VARCHAR(144) NOT NULL UNIQUE,
    HABILITADO CHAR(1) DEFAULT 'H', -- [H] HABILITADO, [D] DESABILITADO

    ID_CONTA CHAR(36) NOT NULL,
    ID_UO CHAR(36) NULL,

    FOREIGN KEY (ID_CONTA) REFERENCES APP_CONTA(ID),
    FOREIGN KEY (ID_UO) REFERENCES APP_UNIDADEORGANIZACIONAL(ID)
);

-- TABELAS BASICAS
CREATE TABLE BAS_CLIENTE (
    ID CHAR(36) NOT NULL PRIMARY KEY
);

CREATE TABLE BAS_FORNECEDOR (
    ID CHAR(36) NOT NULL PRIMARY KEY
);

CREATE TABLE BAS_ATIVOFIXO (
    ID CHAR(36) PRIMARY KEY
);

CREATE TABLE BAS_CENTROCUSTO (
    ID CHAR(36) NOT NULL PRIMARY KEY,
    CODIGO VARCHAR(6) NOT NULL,
    NOME VARCHAR(144) NOT NULL,
    
    ID_CONTA CHAR(36) NOT NULL,
    ID_PAI CHAR(36) NULL,

    FOREIGN KEY (ID_CONTA) REFERENCES APP_CONTA(ID),
    FOREIGN KEY (ID_PAI) REFERENCES BAS_CENTROCUSTO(ID)
);

-- TABELAS DO MODULO CONTAS A PAGAR/RECEBER

-- TABELAS DO MODULO ATIVO FIXO

-- TABELAS DO MODULO CATALOGO DE PRODUTOS/SERVICOS

-- TABELAS DO MODULO DE PEDIDOS DE COMPRA/VENDA

-- TABELAS DO MODULO FINANCEIRO
CREATE TABLE FIN_GRUPO_TRANSACOES (
    ID CHAR(36) NOT NULL PRIMARY KEY,
    NOME VARCHAR(144) NOT NULL,
    HABILITADO CHAR(1) DEFAULT 'H', -- [H] HABILITADO, [D] DESABILITADO

    ID_CONTA CHAR(36) NOT NULL,
    ID_PAI CHAR(36) NULL,

    FOREIGN KEY (ID_CONTA) REFERENCES APP_CONTA(ID),
    FOREIGN KEY (ID_PAI) REFERENCES FIN_GRUPO_TRANSACOES(ID)
);

CREATE TABLE FIN_TRANSACAO (
    ID CHAR(36) NOT NULL,
    CODIGO VARCHAR(6) NOT NULL,
    NOME VARCHAR(144) NOT NULL,
    HABILITADO CHAR(1) DEFAULT 'H', -- [H] HABILITADO, [D] DESABILITADO

    ID_CONTA CHAR(36) NOT NULL,
    ID_GRUPO CHAR(36) NOT NULL,

    CONSTRAINT PK_FIN_TRANSACAO PRIMARY KEY (ID, CODIGO),
    FOREIGN KEY (ID_CONTA) REFERENCES APP_CONTA(ID),
    FOREIGN KEY (ID_GRUPO) REFERENCES FIN_GRUPO_TRANSACOES(ID)
);

CREATE TABLE FIN_EVENTO (
    ID CHAR(36) NOT NULL PRIMARY KEY,
    CODIGO VARCHAR(6) NOT NULL,
    NOME VARCHAR(144) NOT NULL,
    NATUREZA CHAR(1) NOT NULL, -- [E] ENTRADA, [S] SAIDA
    HABILITADO CHAR(1) DEFAULT 'H', -- [H] HABILITADO, [D] DESABILITADO

    ID_TRANSACAO CHAR(36) NOT NULL,

    FOREIGN KEY (ID_TRANSACAO) REFERENCES FIN_TRANSACAO(ID)
);

CREATE TABLE FIN_MOVIMENTO (
    ID CHAR(36) NOT NULL PRIMARY KEY,
    DATA DATE NOT NULL,
    HISTORICO VARCHAR(144) NOT NULL,
    COMPLEMENTO VARCHAR(144),
    ID_FAVORECIDO CHAR(36) NOT NULL,
    TIPO_FAVORECIDO CHAR(1) NOT NULL, -- [F] FORNECEDOR, [C] CLIENTE, [A] ATIVO FIXO

    ID_CONTA CHAR(36) NOT NULL,
    ID_TRANSACAO CHAR(36) NOT NULL,
    ID_EVENTO CHAR(36) NOT NULL,

    FOREIGN KEY (ID_CONTA) REFERENCES APP_CONTA(ID),
    FOREIGN KEY (ID_TRANSACAO) REFERENCES FIN_TRANSACAO(ID),
    FOREIGN KEY (ID_EVENTO) REFERENCES FIN_EVENTO(ID)
);

CREATE TABLE FIN_MOVIMENTO_EVENTOS (
    VALOR INTEGER(10) NOT NULL DEFAULT 0,
    NATUREZA CHAR(1) NOT NULL, -- [E] ENTRADA, [S] SAIDA
    MOEDA CHAR(3) NOT NULL DEFAULT 'BRL', -- CODIGO ISO DE MOEDAS

    ID_MOVIMENTO CHAR(36) NOT NULL,
    ID_TRANSACAO CHAR(36) NOT NULL,
    ID_EVENTO CHAR(36) NOT NULL,
    
    FOREIGN KEY (ID_MOVIMENTO) REFERENCES FIN_MOVIMENTO(ID),
    FOREIGN KEY (ID_TRANSACAO) REFERENCES FIN_TRANSACAO(ID),
    FOREIGN KEY (ID_EVENTO) REFERENCES FIN_EVENTO(ID)
);

-- TABELAS DE SALDOS
-- TODO: TABELAS DE SALDO EM UM BANCO SEPARADO OU NOSQL?

-- TABELAS DE AUDITORIA
-- TODO: CRIAR EM UM BANCO SEPARADO OU NOSQL?

SHOW TABLES;
